//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.34003
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace MU_PuzzleWinPhone8.Resources;

interface

uses
    System;
    
type
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute('System.Resources.Tools.StronglyTypedResourceBuilder', '4.0.0.0')]
    [System.Diagnostics.DebuggerNonUserCodeAttribute]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    AppResources = public class
    private 
        class var resourceMan: System.Resources.ResourceManager;
        class var resourceCulture: System.Globalization.CultureInfo;
        class method get_ResourceManager: System.Resources.ResourceManager;
        class method get_Culture: System.Globalization.CultureInfo;
        class method set_Culture(value: System.Globalization.CultureInfo);
        class method get_AppBarApplyText: System.String;
        class method get_AppBarCancelText: System.String;
        class method get_ApplicationTitle: System.String;
        class method get_BtnCancelLabel: System.String;
        class method get_BtnNextLabel: System.String;
        class method get_BtnOKLabel: System.String;
        class method get_BtnPrevLabel: System.String;
        class method get_CurrStringText: System.String;
        class method get_GoalStringText: System.String;
        class method get_HistoryText: System.String;
        class method get_ResourceFlowDirection: System.String;
        class method get_ResourceLanguage: System.String;
        class method get_Rule1Btn: System.String;
        class method get_Rule1Label: System.String;
        class method get_Rule2Btn: System.String;
        class method get_Rule2Label: System.String;
        class method get_Rule3Btn: System.String;
        class method get_Rule3Label: System.String;
        class method get_Rule4Btn: System.String;
        class method get_Rule4Label: System.String;
    assembly 
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('Microsoft.Performance', 'CA1811:AvoidUncalledPrivateCode')]
        constructor;
    public 
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property ResourceManager: System.Resources.ResourceManager read get_ResourceManager;
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        class property Culture: System.Globalization.CultureInfo read get_Culture write set_Culture;
        class property AppBarApplyText: System.String read get_AppBarApplyText;
        class property AppBarCancelText: System.String read get_AppBarCancelText;
        class property ApplicationTitle: System.String read get_ApplicationTitle;
        class property BtnCancelLabel: System.String read get_BtnCancelLabel;
        class property BtnNextLabel: System.String read get_BtnNextLabel;
        class property BtnOKLabel: System.String read get_BtnOKLabel;
        class property BtnPrevLabel: System.String read get_BtnPrevLabel;
        class property CurrStringText: System.String read get_CurrStringText;
        class property GoalStringText: System.String read get_GoalStringText;
        class property HistoryText: System.String read get_HistoryText;
        class property ResourceFlowDirection: System.String read get_ResourceFlowDirection;
        class property ResourceLanguage: System.String read get_ResourceLanguage;
        class property Rule1Btn: System.String read get_Rule1Btn;
        class property Rule1Label: System.String read get_Rule1Label;
        class property Rule2Btn: System.String read get_Rule2Btn;
        class property Rule2Label: System.String read get_Rule2Label;
        class property Rule3Btn: System.String read get_Rule3Btn;
        class property Rule3Label: System.String read get_Rule3Label;
        class property Rule4Btn: System.String read get_Rule4Btn;
        class property Rule4Label: System.String read get_Rule4Label;
    end;
    
implementation

{ AppResources }

constructor AppResources;
begin
end;

class method AppResources.get_ResourceManager: System.Resources.ResourceManager;
begin
    if System.Object.ReferenceEquals(resourceMan, nil) then begin
        var temp: System.Resources.ResourceManager := new System.Resources.ResourceManager('MU_PuzzleWinPhone8.Resources.AppResources', typeOf(AppResources).Assembly);
        resourceMan := temp;
    end;
    exit(resourceMan);
end;

class method AppResources.get_Culture: System.Globalization.CultureInfo;
begin
    exit(resourceCulture);
end;

class method AppResources.set_Culture(value: System.Globalization.CultureInfo);
begin
    resourceCulture := value;
end;

class method AppResources.get_AppBarApplyText: System.String;
begin
    exit(ResourceManager.GetString('AppBarApplyText', resourceCulture));
end;

class method AppResources.get_AppBarCancelText: System.String;
begin
    exit(ResourceManager.GetString('AppBarCancelText', resourceCulture));
end;

class method AppResources.get_ApplicationTitle: System.String;
begin
    exit(ResourceManager.GetString('ApplicationTitle', resourceCulture));
end;

class method AppResources.get_BtnCancelLabel: System.String;
begin
    exit(ResourceManager.GetString('BtnCancelLabel', resourceCulture));
end;

class method AppResources.get_BtnNextLabel: System.String;
begin
    exit(ResourceManager.GetString('BtnNextLabel', resourceCulture));
end;

class method AppResources.get_BtnOKLabel: System.String;
begin
    exit(ResourceManager.GetString('BtnOKLabel', resourceCulture));
end;

class method AppResources.get_BtnPrevLabel: System.String;
begin
    exit(ResourceManager.GetString('BtnPrevLabel', resourceCulture));
end;

class method AppResources.get_CurrStringText: System.String;
begin
    exit(ResourceManager.GetString('CurrStringText', resourceCulture));
end;

class method AppResources.get_GoalStringText: System.String;
begin
    exit(ResourceManager.GetString('GoalStringText', resourceCulture));
end;

class method AppResources.get_HistoryText: System.String;
begin
    exit(ResourceManager.GetString('HistoryText', resourceCulture));
end;

class method AppResources.get_ResourceFlowDirection: System.String;
begin
    exit(ResourceManager.GetString('ResourceFlowDirection', resourceCulture));
end;

class method AppResources.get_ResourceLanguage: System.String;
begin
    exit(ResourceManager.GetString('ResourceLanguage', resourceCulture));
end;

class method AppResources.get_Rule1Btn: System.String;
begin
    exit(ResourceManager.GetString('Rule1Btn', resourceCulture));
end;

class method AppResources.get_Rule1Label: System.String;
begin
    exit(ResourceManager.GetString('Rule1Label', resourceCulture));
end;

class method AppResources.get_Rule2Btn: System.String;
begin
    exit(ResourceManager.GetString('Rule2Btn', resourceCulture));
end;

class method AppResources.get_Rule2Label: System.String;
begin
    exit(ResourceManager.GetString('Rule2Label', resourceCulture));
end;

class method AppResources.get_Rule3Btn: System.String;
begin
    exit(ResourceManager.GetString('Rule3Btn', resourceCulture));
end;

class method AppResources.get_Rule3Label: System.String;
begin
    exit(ResourceManager.GetString('Rule3Label', resourceCulture));
end;

class method AppResources.get_Rule4Btn: System.String;
begin
    exit(ResourceManager.GetString('Rule4Btn', resourceCulture));
end;

class method AppResources.get_Rule4Label: System.String;
begin
    exit(ResourceManager.GetString('Rule4Label', resourceCulture));
end;

end.
